services:
    - type: web
      name: birth-bridge
      buildCommand: npm ci && npm run build
      staticPublishPath: ./dist
      headers:
          - path: /*
            name: Cache-Control
            value: no-cache
      routes:
          - type: rewrite
            source: /*
            destination: /index.html
